Updated the contributing section
holoviz-topics/examples pull request #355
Opened 2024-01-30 19:44 UTC by Azaya89

This PR modifies the [Contributing section](doc/contributing.md) of the repository to add instructions on how to update an existing project.

2024-02-01 18:59 UTC, maximlt reviewed
Thanks for your PR! I think we can wait a little before merging, I'm sure you'll have more to add when you will really update your next project. I also think it'd be good to get @jtao1 's feedback (later), he may suggest other steps to add or updates.

2024-02-02 07:58 UTC, Azaya89 commented
> Thanks for your PR! I think we can wait a little before merging, I'm sure you'll have more to add when you will really update your next project. I also think it'd be good to get @jtao1 's feedback (later), he may suggest other steps to add or updates.

I agree. I'm already seeing more steps that need to be added :)

2024-03-14 06:35 UTC, maximlt requested changes

2024-03-14 06:35 UTC, maximlt commented on doc/contributing.md
I think the setup should include:

1. Cloning the repo
2. Creating the dev environment

2024-03-14 06:35 UTC, maximlt commented on doc/contributing.md
We should let the contributors know they should always start with opening an issue.

This is also needed because at the moment the system cannot deal with contributors who don't have some rights on the repository (https://github.com/holoviz-topics/examples/issues/353). We don't necessarily have to indicate that (hopefully this will one day be fixed).

2024-03-14 21:28 UTC, Azaya89 commented on doc/contributing.md
> +3. Open the built site:
OK.

2024-03-20 15:48 UTC, maximlt approved these changes
Thanks!

2024-03-20 15:49 UTC, merged