Modernize portfolio optimizer
holoviz-topics/examples pull request #376
Opened 2024-04-03 07:20 UTC by jtao1

Submitted first update on portfolio optimizer. Some things that I still need to do:
- added better explanations for the code especially the newer ones related to creating the panel app
- remove possibly redundant math when creating the graphs

2024-04-11 22:32 UTC, maximlt requested changes
I have reviewed the PR. Before adding general comments, I wanted to ask you the status of these tasks you wanted to complete?

> Submitted first update on portfolio optimizer. Some things that I still need to do:
> 
>     * added better explanations for the code especially the newer ones related to creating the panel app
> 
>     * remove possibly redundant math when creating the graphs

Comments after review:

- It took me a little while to get what `252` stood for, it turns out it's the number of trading days in a year. Make this a little clearer in the notebook please.
- The first part of the example, that was already there, is quite dry. I don't think spending time improving that is really in the scope of our work, unless that's something that would be quick and easy for you to do!
- However, I think the introduction could be improved. At the moment it only talks about the financial aspect of the example, it could be extended a little to describe the HoloViz tools that are going to be used (hvplot, holoviews, panel) and how they support the analysis. It should also be mentioned a Panel dashboard is going to be created. Adding a screenshot of this app at the beginning would be nice (check out Isaiah's PR on `nyc_taxi` and the start of the `dashboard.ipynb` notebook).
- My main feedback: the section you have ported from Panel's website is also very dry. We need to add some explanation about the app we are building and how we are building it. The `Build a <app>` tutorials you have recently gone through could be a good template for this.
- We should add this app as a deployment (check out `./template/anaconda-project.yaml` to see how). And if we do that, we could also wrap it in a template at the very end of the notebook, so the deployed app looks good.
- Some of the elements of the app could be made responsive (i.e. set up so they dynamically stretch to occupy the available space).
- The app is built using hvPlot's interactive API. It's possible we'll try to migrate to `pn.rx`. I'm waiting for feedback from others on Discord on this point.

EDIT: I updated your original post with the modernizing checklist.

2024-04-18 20:23 UTC, maximlt commented
I have a suggestion about the notebook being a little dry and lacking context. Maybe you could throw the notebook content at ChatGPT and ask for it to add some brief explanations about the underlying analysis. That's just a suggestion, so feel free to ignore it if you don't feel like it. I think though that ChatGPT could do a good job at this, given this is I believe a very common kind of analysis.

2024-04-29 18:14 UTC, jbednar commented
> It's possible we'll try to migrate to pn.rx

Is there anyone who is arguing for keeping it hvplot.interactive? pn.rx seems like the obvious thing to do, unless someone is very convincingly arguing otherwise.

2024-05-01 13:33 UTC, jtao1 commented on portfolio_optimizer/portfolio_optimizer.ipynb
> +    "import panel as pn"
This has been merged.

2024-05-14 23:40 UTC, ahuang11 commented
Was helping Jason with `rx` and it felt like `rx` was a bit magical / unintuitive to me.

Also, we weren't sure how to separate out the widgets to better lay out the dashboard, unlike pn.Param.

I'm -1 on using `rx` and prefer `pn.bind` way more.

```python
from io import BytesIO
import pandas as pd
import panel as pn
pn.extension()

@pn.cache
def get_stocks(data):
    if data is None:
        stock_file = 'https://datasets.holoviz.org/stocks/v1/stocks.csv'
    else:
        stock_file = BytesIO(data)
    return pd.read_csv(stock_file, index_col='Date', parse_dates=True)


file_input = pn.widgets.FileInput(sizing_mode='stretch_width')

stocks = pn.rx(get_stocks)(file_input)

selector = pn.widgets.MultiSelect(
    name='Select stocks', sizing_mode='stretch_width',
    options=stocks.columns.to_list()
)

selected_stocks = stocks.rx.pipe(
    lambda df, cols: df[cols] if cols else df, selector
)

pn.Column(selected_stocks)
```
<img width="1025" alt="image" src="https://github.com/holoviz-topics/examples/assets/15331990/96505c00-4c0f-4b1e-ba01-e5d2f3cad88a">

Lastly, upon printing rx objects, it raises an error
https://github.com/holoviz/param/issues/939

2024-05-14 23:48 UTC, ahuang11 commented
Ok I just realized there's a [section in Panel about rx](https://panel.holoviz.org/tutorials/basic/pn_rx.html); I was too focused on the param docs.

To split the widget + column, you need to wrap it in the corresponding pane; personally I'd prefer a method to call to do so, e.g. `selected_stocks.get_pane()`

```
from io import BytesIO
import pandas as pd
import panel as pn
pn.extension()

@pn.cache
def get_stocks(data):
    if data is None:
        stock_file = 'https://datasets.holoviz.org/stocks/v1/stocks.csv'
    else:
        stock_file = BytesIO(data)
    return pd.read_csv(stock_file, index_col='Date', parse_dates=True)


file_input = pn.widgets.FileInput(sizing_mode='stretch_width')

stocks = pn.rx(get_stocks)(file_input)

selector = pn.widgets.MultiSelect(
    name='Select stocks', sizing_mode='stretch_width',
    options=stocks.columns.to_list()
)

selected_stocks = stocks.rx.pipe(
    lambda df, cols: df[cols] if cols else df, selector
)

pn.Column(
    pn.Row(file_input, selector),
    pn.pane.DataFrame(selected_stocks),
)
```

2024-05-15 05:19 UTC, jtao1 commented on portfolio_optimizer/portfolio_optimizer.ipynb
> +    "log_ret_hists = log_ret.hvplot.hist(bins=100, subplots=True, width=400, group_label='Ticker', grid=True).cols(2)\n",
I've made the change for spreading the code over two lines.

2024-05-22 12:19 UTC, maximlt submitted a review, later dismissed

2024-05-22 15:50 UTC, jbednar commented
> @ahuang11 : Ok I just realized there's a [section in Panel about rx](https://panel.holoviz.org/tutorials/basic/pn_rx.html); I was too focused on the param docs.

Can you please make a PR on Param putting in an explicit link to the Panel rx docs wherever you would have found them? Right now it only links to the main Panel site, but pointing directly to Panel rx info would presumably prevent others from having the same experience you did.

2024-05-29 01:34 UTC, jtao1 commented on portfolio_optimizer/portfolio_optimizer.ipynb
> +    "scatter = data.hvplot.scatter(x='Volatility', y='Return', c='Sharpe Ratio', cmap='plasma', width=600, height=400, colorbar=True, padding=0.1)\n",
I reduced the marker size to 25, I thought 10 looked too small.

2024-05-29 02:36 UTC, jtao1 commented on portfolio_optimizer/portfolio_optimizer.ipynb
> +    "stocks = hvplot.bind(get_stocks, file_input).interactive()\n",
Done!

2024-05-29 02:36 UTC, jtao1 commented on portfolio_optimizer/portfolio_optimizer.ipynb
> +    "pn.extension('tabulator', design='material', template='material', theme_toggle=True, loading_indicator=True)\n",
Done!

2024-06-04 02:12 UTC, jtao1 commented on portfolio_optimizer/portfolio_optimizer.ipynb
Done

2024-06-04 02:14 UTC, jtao1 commented on portfolio_optimizer/portfolio_optimizer.ipynb
> +    "Portfolio Optimization helps risk-averse investors construct portfolios to maximize expected return given a certain level of market risk, emphasizing the inherent relationship between risk and r
Oh yep, your way makes the sentence clearer.

2024-06-20 17:46 UTC, droumis commented
I made a lot of changes. This PR wasn't really close to being ready for a final review.

2024-06-20 17:58 UTC, droumis commented on portfolio_optimizer/portfolio_optimizer.ipynb
there were still heading errors. I think I caught the rest

2024-06-20 18:37 UTC, droumis approved these changes

2024-06-20 18:37 UTC, merged